name: "build"
on:
  pull_request:
  push:
    branches:
      - '*'

env:
  ONTRACK_URL: ${{ secrets.ONTRACK_URL }}
  ONTRACK_TOKEN: ${{ secrets.ONTRACK_TOKEN }}

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  # using this action for this project
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          logging: true
      - run: echo Ontrack GitHub repository = $ONTRACK_GITHUB_REPOSITORY
